---
kind: pipeline
type: docker
name: ProjectEQ Quests CI

steps:
  - name: project-eq-script-ci-run
    image: debian:stretch-slim
    commands:
      - apt-get update > /dev/null && DEBIAN_FRONTEND=noninteractive apt-get install -yq lua5.1 perl libdbi-perl libswitch-perl libdbd-mysql-perl libjson-perl 2> /dev/null
      - ./ci.sh
